### ISSUE TITLE
getManyAndCount don't return existing rows in db

### ISSUE THREAD

**Issue by leandroluk** [typeorm/typeorm#10497]
### Issue description

getManyAndCount don't return existing rows in db

### Expected Behavior

I have a Postgres DB with this data: 

```sql
CREATE TABLE "user" (
  "id" UUID NOT NULL DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
  "email" VARCHAR(100) NOT NULL UNIQUE,
  "password" TEXT NOT NULL
);
INSERT INTO "user" ("email", "password") VALUES ('a@a.com', '123456');
```

And this slice of code:

```ts
import "reflect-metadata";
import { Column, DataSource, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn('uuid') id!: string;
  @Column({ type: 'varchar', length: 100 }) email!: string;
  @Column({ type: 'text' }) password!: string;
}

const dataSource = new DataSource({
  type: 'postgres',
  url: 'postgresql://postgres:postgres@localhost:5432/postgres',
  synchronize: false,
  entities: [UserEntity],
});

const run = async () => {
  await dataSource.initialize();
  const [items, total] = await dataSource.createQueryBuilder().from(UserEntity, 'x').getManyAndCount();
  console.log({ items: items.length, total });
};
run();
```

### Actual Behavior

The code results in 0 rows but exists 1 row in database. If i'm use the function `getMany()` always return a empty array but the function `getRawMany()` returns 1 row

### Steps to reproduce

> You will need docker to run this test

1. Create a node project:
   ```
   npm init -y
   ```

2. Install the dependencies for a minimal Typescript project with Postgres and TypeORM:
   ```
   npm add ts-node typescript typeorm reflect-metadata @types/node pg
   ```

3. Initialize the typescript project
   ```
   npx tsc --init
   ```

4. change the `tsconfig.json` to enable features used by typeorm decorators:
   ```json
   {
      "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
      }
   }
   ```

5. Create the `<rootDir>/db.sql`:
   ```
   CREATE TABLE "user" (
     "id" UUID NOT NULL DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
     "email" VARCHAR(100) NOT NULL UNIQUE,
     "password" TEXT NOT NULL
   );
   INSERT INTO "user" ("email", "password") VALUES ('a@a.com', '123456');
   ```

6. Create the `<rootDir>/docker-compose.yml`:
   ```yaml
   version: '3'
   services:
     postgres:
       image: postgres
       hostname: postgres
       container_name: postgres
       ports: [ '5432:5432' ]
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: postgres
       volumes: [ './db.sql:/docker-entrypoint-initdb.d/db.sql' ]
       healthcheck:
         test: ['CMD-SHELL', 'pg_isready -U postgres']
         interval: 10s
         timeout: 5s
         start_period: 10s   
   ```

8. Create the example inserted in "Expected Behavior" of this issue:
   ```ts
   import "reflect-metadata";
   import { Column, DataSource, Entity, PrimaryGeneratedColumn } from 'typeorm';
 
   @Entity('user')
   export class UserEntity {
     @PrimaryGeneratedColumn('uuid') id!: string;
     @Column({ type: 'varchar', length: 100 }) email!: string;
     @Column({ type: 'text' }) password!: string;
   }
 
   const dataSource = new DataSource({
     type: 'postgres',
     url: 'postgresql://postgres:postgres@localhost:5432/postgres',
     synchronize: false,
     entities: [UserEntity],
   });
 
   const run = async () => {
     await dataSource.initialize();
     // wrong
     const r1 = await dataSource.createQueryBuilder().from(UserEntity, 'x').getManyAndCount();
     console.log({ fn: 'getManyAndCount', items: r1[0].length, total: r1[1] });
     // wrong
     const r2 = await dataSource.createQueryBuilder().from(UserEntity, 'x').getMany();
     console.log({ fn: 'getMany', items: r2.length, });
     // correct
     const r3 = await dataSource.createQueryBuilder().from(UserEntity, 'x').getRawMany();
     console.log({ fn: 'getRawMany', items: r3.length, });    
   };
   run();
   ```

9. Run the program and see the wrong result in console. 
   ```
   { fn: 'getManyAndCount', items: 0, total: 1 }
   { fn: 'getMany', items: 0 }
   { fn: 'getRawMany', items: 1 }
   ```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows |
| Node.js version     | v20.9.0  |
| Typescript version  | 5.2.2 |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.
