### ISSUE TITLE
TypeORM Cache with Redis Cluster throws errors

### ISSUE THREAD

**Issue by starci183** [typeorm/typeorm#11224]
### Issue description

TypeORM Cache with Redis Cluster throws errors Unexpected error processing request: Error: MOVED 4035 10.0.2.16:6379

### Expected Behavior

Cached successfully

### Actual Behavior

Throws error: Unexpected error processing request: Error: MOVED 4035 10.0.2.16:6379

### Steps to reproduce

I have run 6 instances of Redis Clusters (3 masters, 3 slaves), they work well in Docker.

I have also try to use [redis/ioredis](https://www.npmjs.com/package/ioredis) to test connection. 

```
const connection = new Cluster([
            {   
                host: "127.0.0.1",
                port: 6379
            }
        ], {
            natMap: {
                "172.25.0.7:6379": { host: "127.0.0.1", port: 6382 },  // Slave node
                "172.25.0.3:6379": { host: "127.0.0.1", port: 6381 },  // Master node (slot range: 5461-10922)
                "172.25.0.2:6379": { host: "127.0.0.1", port: 6379 },  // Slave node
                "172.25.0.4:6379": { host: "127.0.0.1", port: 6384 },  // Master node (slot range: 0-5460)
                "172.25.0.6:6379": { host: "127.0.0.1", port: 6380 },  // Slave node
                "172.25.0.5:6379": { host: "127.0.0.1", port: 6383 }   // Master node (slot range: 10923-16383)
            }
        })
        const x = await connection.set("foo", "bar")
        console.log(x)
```
It works.
But when i set the similar config to typeorm cache options, it fails.
```
        options: {
                startupNodes: [
                    {
                         host: "127.0.0.1",
                         port: 6379
                    }
                ],
                natMap: {
                "172.25.0.7:6379": { host: "127.0.0.1", port: 6382 },  // Slave node
                "172.25.0.3:6379": { host: "127.0.0.1", port: 6381 },  // Master node (slot range: 5461-10922)
                "172.25.0.2:6379": { host: "127.0.0.1", port: 6379 },  // Slave node
                "172.25.0.4:6379": { host: "127.0.0.1", port: 6384 },  // Master node (slot range: 0-5460)
                "172.25.0.6:6379": { host: "127.0.0.1", port: 6380 },  // Slave node
                "172.25.0.5:6379": { host: "127.0.0.1", port: 6383 }   // Master node (slot range: 10923-16383)
            }
      }
```
It fails. And the error is `Error: MOVED 4035 10.0.2.16:6379`.
As I know, this error is created when use `redis-cli` without `-c`, Redis cluster can auto redirect to correct slot. So that maybe it a bug from typeorm code or wrong depencies?

        

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 23.3.0  |
| Typescript version  | ^5.1.3  |
| TypeORM version     |  "0.3.20",  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by OSA413** [comment]
Hi! Can you please provide a repository with all things configured (minimal reproducible example) so we can easily investigate the issue?

**Comment by starci183** [comment]
> Hi! Can you please provide a repository with all things configured (minimal reproducible example) so we can easily investigate the issue?

[minimal reproducible example](https://github.com/starci-lab/redis-cluster-minimal)
Here is the minimal reproducible example.

You can install my cluster via [https://github.com/starci-lab/redis-cluster-minimal/blob/main/installrediscluster.sh](https://github.com/starci-lab/redis-cluster-minimal/blob/main/installrediscluster.sh) and the postgres
`docker run --name some-postgres -e POSTGRES_PASSWORD=Cuong123_A -p 5432:5432 -d postgres`
I use docker for both.

I have do testing for both case: ioredis and typeorm in file [https://github.com/starci-lab/redis-cluster-minimal/blob/main/src/app.service.ts](https://github.com/starci-lab/redis-cluster-minimal/blob/main/src/app.service.ts).

P/S: Sometime it throws the above errors, sometime it stuck despite i have set timeout error.

**Comment by wis-dev** [comment]
Same issue here!

I try many different ways and none of them work.

Using this config on my `data-source.ts` file:

```
cache: {
	type: 'redis',
	options: {
		socket: {
			host: process.env.REDIS_HOST,
			port: 7000
		}
	}
}
```

❌ ERROR: `"MOVED 7811 redis-7001:7001"`

---

Then i switch to `ioredis/cluster` with the following config:

```
cache: {
	type: "ioredis/cluster",
	options: {
		startupNodes: [
			{
				host: process.env.REDIS_HOST,
				port: 7000,
			},
			{
				host: process.env.REDIS_HOST,
				port: 7001,
			},
			{
				host: process.env.REDIS_HOST,
				port: 7002,
			}
		],
		options: {
			scaleReads: 'all',
			clusterRetryStrategy: function (times) { return null },
			redisOptions: {
				maxRetriesPerRequest: 1
			}
		}
	}
}
```

❌ ERROR: `"Connection is closed."`

---

So i try another way, changing `redis` with `ioredis`

```
cache: {
	type: 'ioredis',
	options: {
		socket: {
			host: process.env.REDIS_HOST,
			port: 7000
		}
	}
}
```

❌ ERROR: 
```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
```

---

And with my last bullet i set this another config:

```
cache: {
	type: "ioredis/cluster",
	options: [
		{
			host: process.env.REDIS_HOST,
			port: 7000,
		},
		{
			host: process.env.REDIS_HOST,
			port: 7001,
		},
		{
			host: process.env.REDIS_HOST,
			port: 7002,
		}
	]
}
```

❌ ERROR: `Error: Timeout was reached`

---

### My Environment

- Node.js version: 22.0.0
- Typescript version	^5.7.3
- TypeORM version	0.3.20
- ioredis: 5.5.0
- redis: ^4.7.0

Also I am using redis `8.0-M03-alpine` deployed on Docker with 3 replicas.

This is a part of my `docker-compose.yml` file:

```
version: '3.9'

services:
  redis-7000:
    image: redis:8.0-M03-alpine
    container_name: redis-7000
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - redis-data-7000:/data
    command:
      - "redis-server"
      - "--bind"
      - "0.0.0.0"
      - "--port"
      - "7000"
      - "--cluster-enabled"
      - "yes"
      - "--cluster-config-file"
      - "nodes.conf"
      - "--cluster-node-timeout"
      - "5000"
      - "--appendonly"
      - "yes"
      - "--protected-mode"
      - "no"
      - "--cluster-slave-validity-factor"
      - "60"
      - "--cluster-announce-ip"
      - "redis-7000"
      - "--cluster-announce-port"
      - "7000"
      - "--cluster-announce-bus-port"
      - "17000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - redis-cluster-network
  // ...
```
