### ISSUE TITLE
Data Fixtures

### ISSUE THREAD

**Issue by fridolin-koch** [typeorm/typeorm#1550]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

--

I've checked the docs but was not able to find anything related to data fixtures. I've used doctrine/symfony for some years and they have the https://github.com/doctrine/data-fixtures package in their ecosystem. Is there something similar for typeorm? This would be quite useful e.g. for populating the database with defaults or test data.

Thanks!

**Comment by pleerock** [comment]
Simply create a migration and write database population logic there. Use packages like [faker](https://www.npmjs.com/package/faker) to create a fake data. Its basically the same as data fixtures you are asking about.

**Comment by fridolin-koch** [comment]
All right thanks for the answer, I'll try that.

**Comment by ant45de** [comment]
I don't think fixtures should be part of migrations.
Is there currently any other official way to create fixtures?

**Comment by pleerock** [comment]
why they can't?

**Comment by bitwit** [comment]
I was recently trying to solve this and came up with a pretty simple solution.

First i made a `loadFixtures` function: 
```typescript
import { Connection, Repository } from "typeorm"
import * as yaml from 'js-yaml'
import * as fs from 'fs'

export async function loadFixtures(name: string, dbConnection: Connection): Promise<any> {

    let items: any[] = []
    try {
        const file: any = yaml.safeLoad(fs.readFileSync(`./test/fixtures/${name}.yml`, 'utf8'));
        console.log(file)
        items = file["fixtures"]
    } catch (e) {
        console.log("fixtures error", e);
    }

    if(!items) {
        return
    }

    items.forEach(async (item: any) => {
        const entityName = Object.keys(item)[0]
        const data = item[entityName]
        const repo = dbConnection.getRepository(entityName) 
        const newEntity = repo.create(data)
        await repo.createQueryBuilder().insert().into(entityName).values(data).execute()
    })
}
```

And I can load yaml files like this now:

```yaml
fixtures:
    - User:
        id: 1
        email: t@t1.com
        password: "$2a$12$AeLkrNG2Lje156hKYft/CurW8xm/2gGq2Z26OKOwpeIn3XabfM3.." # 12345678
    - User:
        id: 2
        email: second@user.com
        password: "$2a$12$AeLkrNG2Lje156hKYft/CurW8xm/2gGq2Z26OKOwpeIn3XabfM3.." # 12345678
```

I tried using repos directly instead of query builder but ran into some strange issues with duplicate insertions. Once i switched the query builder the problem went away. Not sure if you see any potential pitfalls to a solution like this @pleerock but I just wanted to shared anyway for those who may not want to use migrations.

Personally, I agree it's nicer to keep them out. My fixtures exist in the `test/` folder just as data files. I like yaml for minimal syntax and inline commenting.

TypeORM is great to work with so far, BTW!

**Comment by bitwit** [comment]
I updated the code posted above for some issues I noticed with it plus wanted to note a few things I came across using this technique:

1. I had a problem using `@PrimaryGeneratedColumn("uuid")`, but regular `@PrimaryGeneratedColumn()` was fine. So for uuid's I switched to `@PrimaryColumn` and generated them myself in the constructor.
2. When referring to other tables continue to pass the data as an object: i.e.
```
fixtures:
    - User:
        id: 1
        email: t@t1.com
        password: "$2a$12$AeLkrNG2Lje156hKYft/CurW8xm/2gGq2Z26OKOwpeIn3XabfM3.." # 12345678
        profile: 
          id: 1
```
In this case there is a `User` related to a `Profile` object and you are trying to set the `profileId` column on the `User`. Using `profileId` directly will fail. 
3. Just a reinforced reminder you aren't setting the columns directly through querybuilder. It got me around headaches that `.save()` was causing but it is not raw access to the database.
