### ISSUE TITLE
ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by huanz** [typeorm/typeorm#1955]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

```ts
@Column({
    unique: true
})
url: string;
```

**Comment by huanz** [comment]
@pleerock I think the default length is a problem

```typescript
@Column({
    unique: true,
    length: 150
})
url: string;
```

This error will not be triggered。

#1139

**Comment by kelmore5** [comment]
For anyone stumbling upon this in the future...

I had to set the "charset" and "collation" options in the Column decorator like so:

`@Column({length: 2048, unique: true, charset: 'latin1', collation: 'latin1_swedish_ci'})`

before my key worked.

**Comment by wf9a5m75** [comment]
For the people who reached out here (including myself in the future).

Here is the description.
You must be used `mysql` or `mariadb`, because this error is related to `mysql` itself.

The simple solution is `upgrade your mysql DB greater than or equal 5.7` (In `mariadb`, use the latest (at least `mariadb:10.11.2` is fine)).

--------------

I guess you specify `utf8mb4` for charset. That's the reason.

>767 bytes in MySQL version 5.6 (and prior versions), is the [stated prefix limitation](http://dev.mysql.com/doc/refman/5.1/en/create-index.html) for InnoDB tables. It's 1,000 bytes long for MyISAM tables. This limit has been increased to 3072 bytes In MySQL version 5.7 (and upwards).

[source: stackoverflow](https://stackoverflow.com/a/1814594)

And `because 767 / 4 ~= 191 , and 767 / 3 ~= 255`
[source: stackoverflow](https://stackoverflow.com/a/31474509)

------------

In my case, I specify in the `docker-compose.yml` like below.
```yml
  mysql:
    image: mariadb:10.1.26
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
```

And change to
```yml
  mysql:
    image: mariadb:10.11.2
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
```

-------

And the people who CANNOT change the database, specify the limit like @kelmore5. Should be fine.

```typescript
@Entity()
export class User{

  @Column({length: 191})
  userId: string;

  ...
}
```
