### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE after upgrade

### ISSUE THREAD

**Issue by OysteinAmundsen** [typeorm/typeorm#2093]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm deploying my code to Azure using docker cloud. Before upgrading TypeOrm, this was smooth sailing. After upgrading TypeORM from 0.1.21 to 0.2.5, I get this obscure error message: 
```
typeorm migration:run

Error during migration run:
{ Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/usr/src/app/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/usr/src/app/node_modules/mysql/lib/Pool.js:48:16)
    at /usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:694:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:691:16)
    at MysqlDriver.<anonymous> (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:250:51)
    at step (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:32:23)
    at Object.next (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:13:53)
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! migrations:run: `typeorm migration:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the migrations:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My working (before typeorm upgrade) stack file is this:

```
db:
  image: 'mysql:latest'
  restart: on-failure
  environment:
    - MYSQL_DATABASE=myDB
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=myuser
  volumes:
    - '/usr/src/app/data:/var/lib/mysql'
client:
  image: 'dockerhubuser/client:latest'
  autodestroy: on-success
  autoredeploy: true
  restart: on-failure
  environment:
    - DATABASE_HOST=db
    - NODE_ENV=production
  links:
    - db
  volumes:
    - '/usr/src/app/log:/usr/src/app/log'
    - '/usr/src/app/media:/usr/src/app/media'
nginx:
  image: 'dockerhubuser/nginx'
  autodestroy: on-success
  autoredeploy: true
  restart: on-failure
  environment:
    - TZ=UTC
  links:
    - client
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - '/usr/src/app/cert/ssl:/etc/nginx/ssl'
```

My ormconfig.json
```
[
  {
    "name": "default",
    "environment": "production",
    "type": "mysql",
    "host": "db",
    "port": 3306,
    "username": "myuser",
    "password": "password",
    "database": "myDB",
    "logging": "error",
    "entities": [
      "dist/model/*.js"
    ],
    "migrations": [
      "dist/migrations/*.js"
    ],
    "cli": {
      "migrationsDir": "src/server/migrations"
    },
    "synchronize": true
  }
]
```

I've tried exposing the mysql container and connecting to it using mysql workbench works fine. I thought the volume containing the table files was corrupt, so I removed the data in the volume to get a clean start, but to no avail. The database was cleaned up, but typeorm migrations still cannot run. 

Am I doing something wrong?

For reference, this is my repo: https://github.com/OysteinAmundsen/gymsystems

**Comment by OysteinAmundsen** [comment]
Is this by any chance connected to this issue: https://github.com/mysqljs/mysql/issues/1507 ?

**Comment by OysteinAmundsen** [comment]
Looking at the information in the linked issue above, I tried to set the following in my `ormconfig.json`:
```
"insecureAuth": true
```
But this did nothing to improve on the error. :-( Besides, I have done nothing to tweak the defaults in neither the mysql image nor typeorm. 

The really weird thing is that this is not an issue when running the same docker containers locally on a windows box. This is just an issue when deployed to my Ubuntu instance in Azure... And since that is my production server, this issue is kind of a drag. The site is basically down because of this.

**Comment by pleerock** [comment]
try to do:

```ts
{
   "extra": { "insecureAuth": true }
}
```

in your ormconfig

**Comment by OysteinAmundsen** [comment]
Didn't seem to have any effect. :-(

**Comment by pleerock** [comment]
Then I suggested to downgrade mysql driver version to what you used before, and even if that don't work try to setup a connection with mysql package only and check if issue still reproducible

**Comment by nerder** [comment]
the docker image of mysql change latest as MySQL8, try to hardcode in your `docker-compose.yml` `mysql:5.6` instead of using `mysql:latest`

**Comment by deimsdeutsch** [comment]
Still Not working on mysql but working on mariadb

**Comment by RodrigoLeiteF** [comment]
Still not working.

**Comment by Las-Wonho** [comment]
My system works using [this comment](https://github.com/mysqljs/mysql/issues/1507#issuecomment-385224467)

**Comment by peterramaldes** [comment]
Same here

**Comment by fwchen** [comment]
same

**Comment by pleerock** [comment]
guys saying "same", can you please specify your mysql version?

**Comment by fwchen** [comment]
mysql 8.0.14 (Linux   (x86_64))

**Comment by fwchen** [comment]
I found a solution for docker.

``` bash
docker run --name some-mysql \
-p 3306:3306 \
-e MYSQL_ROOT_PASSWORD=my-secret-pw \
-d mysql \
--default-authentication-plugin=mysql_native_password
```

`--default-authentication-plugin=mysql_native_password`

**Comment by GillesWHC** [comment]
I've got the same issue on mysql 5.6.43, mysql 8.0.15 & mariadb 10.4.3.

**Comment by luckcoding** [comment]
i solved on v8 (mac)
`$ mysql -u root -p`
`$ mysql > ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '12345678';`
`$ mysql > FLUSH PRIVILEGES;`

**Comment by marcusjwhelan** [comment]
even with the authentication command I still get this error
- mysql:8.0.19

@fwchen 
I don't think a good solution to fixing this is manually fixing the user within the container. The container shouldn't need me to go in and fix it. It should startup and work with the correct commands in place. You know. For testing and local dev. I don't want to have to do this all the time.
```
version: "3.7"

services:
    db:
        container_name: mysql_comp_dev
        build:
            context: ./db-service
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ctodo
            MYSQL_ROOT_PASSWORD: ~Example1~
        restart: always
        hostname: db
        networks:
            node_mysql_network:
        ports:
            - 3307:3306
        volumes:
            - $HOME/docker/volumes/node_mysql/:/var/lib/mysql/
    api:
        container_name: node_comp_dev
        hostname: api
        build:
            context: .
            dockerfile: Dockerfile.dev
        networks:
            - node_mysql_network
        environment:
            PORT: 8080
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: ~Example1~
            MYSQL_DB: ctodo
            MYSQL_PORT: 3306
        ports:
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        stdin_open: true
        tty: true
        entrypoint: sh
        restart: always
        depends_on:
            - db
networks:
    node_mysql_network:

volumes:
    db_data:
        driver: local
```
