### ISSUE TITLE
"Connection terminated unexpectedly" when running migration:run on Bitbucket Pipeline

### ISSUE THREAD

**Issue by ripper234** [typeorm/typeorm#2580]
**Issue type:**

[ X] question

**Database system/driver:**

[ X] `postgres`

**TypeORM version:**

[ X] `0.2.7` 

**Steps to reproduce or a small repository showing the problem:**

We have a small migration script that creates a few tables.
On development machines it works flawlessly.
We are now setting up a Bitbucket Pipeline setup, and getting this stack trace there.
Perhaps you have a clue to why this is happening on Bitbucket and not on all developer machines?

```
typeorm migration:run
Error during migration run:
Error: Connection terminated unexpectedly
    at Connection.con.once (/opt/atlassian/pipelines/agent/build/node_modules/pg/lib/client.js:179:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Connection.emit (events.js:208:7)
    at Socket.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/pg/lib/connection.js:128:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1
```

Our bitbucket-pipleline.xml is quite simple (note, ``db migrate`` just calls ``typeorm migration:run``):

```
image: node:8.11.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - cp .env.example .env
          - docker run -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=titan --name postgres -p 5432:5432 -d postgres:10.4
          - yarn
          - yarn db:migrate
          - yarn test
        services:
          - docker
```
