### ISSUE TITLE
Read charset config from environment variables

### ISSUE THREAD

**Issue by spacemeowx2** [typeorm/typeorm#2885]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In my docker-compose.yml

```yml
...
services:
  database:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
      - MYSQL_ROOT_PASSWORD=example
  myprogram:
    # ...
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=database
      - TYPEORM_USERNAME=example
      - TYPEORM_PASSWORD=example
      - TYPEORM_DATABASE=example
      - TYPEORM_ENTITIES=src/entity/**/*.ts
      - TYPEORM_MIGRATIONS=src/migration/**/*.ts
```

I want to tell `typeorm` to use `utf8mb4` via environment variables.

Or consider using environment variables to override the configuration file.

https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/src/driver/mysql/MysqlConnectionOptions.ts#L21
