### ISSUE TITLE
TypeOrm entity does not create tables 

### ISSUE THREAD

**Issue by sptGabriel** [typeorm/typeorm#5723]
**Issue type:**

[x ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Entity is not created when starting my project as can be seen here:**

postgres-# \d emasa_base
Did not find any relation named "emasa_base".
I can't imagine where the problem is I have a User entity:

```
@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column()
  email: string;

  @Column()
  age: number;

  @Column("timestamp")
  register_at: Date;
}

```
**my tpyeorm ormconfig settings:**

```
{
  "type": "postgres",
  "host": "db",
  "port": 5432,
  "username": "spirit",
  "password": "emasa",
  "database": "emasa_base",
  "synchronize": true,
  "logging": false,
  "entities": ["src/entity/**/*.ts"],
  "migrations": ["src/migration/**/*.ts"],
  "subscribers": ["src/subscriber/**/*.ts"],
  "cli": {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
}
```

**my index.ts**

```
const startServer = async () => {
  const server = new ApolloServer({
    schema,
    context: ({ req, res }: any) => ({ req, res })
  });
  let retries = 5;
  while (retries) {
    try {
      await createConnection();
      break;
    } catch (err) {
      console.log(err);
      retries -= 1;
      console.log(`retries left: ${retries}`);

      await new Promise(res => setTimeout(res, 5000));
    }
  }
  const app = express();

  server.applyMiddleware({ app });

  app.listen({ port: process.env.SERVER_PORT }, () =>
    console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`)
  );
};

startServer();
```

**my dockercompose:**

```
version: "3.7"
services:
  db:
    image: postgres:12
    restart: always
    container_name: "db"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: "pgadmin4"
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: emasa@emasa.com
      PGADMIN_DEFAULT_PASSWORD: admin

  api:
    image: server_emasa
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
volumes:
  db_data:
```

**my docker file:**

```
FROM node as builder
WORKDIR usr/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn run build


FROM node
WORKDIR usr/app
COPY package*.json ./
RUN yarn install --production

COPY --from=builder /usr/app/dist ./dist

COPY ormconfig.docker.json ./ormconfig.json
COPY .env . 

expose 4000
CMD node dist/src/index.js
```

my node server starts normally I can access localhost: 4000 / graphql and also my postgres, but for some reason the table is not being created I believe the problem is in my docker file or my orm config

on my logs my node serv:

```
api        | �🚀 Server ready at http://localhost:4000/graphql
last my folder structures:
```

![image](https://user-images.githubusercontent.com/58380116/77118449-fb856380-6a12-11ea-8e58-e99985f72e47.png)
