### ISSUE TITLE
Problem running a migration with github actions

### ISSUE THREAD

**Issue by JeffersonCarvalh0** [typeorm/typeorm#6005]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

I have a koa app with typeorm as ORM and jest as the test runner, along with supertest. I have several tests to this app that involve calls to the endpoints I have exposed, and the controllers of those endpoints use typeorm to communicate with the postgres database. Everything is running well in my machine, but now I'm trying to setup a github action that runs those tests before deploying the app. In order for it to work, I have configured postgres in my workflow with the same credentials I have in my ormconfig. The problem is, right before the tests, I try to run a migration, and I'm getting the following error:

```
yarn run v1.22.4
$ yarn workspace server test
$ NODE_ENV=test && yarn migration:run && jest
$ yarn ts-node ../../node_modules/typeorm/cli.js migration:run
$ /home/runner/work/todo-app/todo-app/node_modules/.bin/ts-node ../../node_modules/typeorm/cli.js migration:run
Error during migration run:
error: password authentication failed for user "runner"
    at Connection.parseE (/home/runner/work/todo-app/todo-app/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/home/runner/work/todo-app/todo-app/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/home/runner/work/todo-app/todo-app/node_modules/pg/lib/connection.js:116:22)
    at Socket.emit (events.js:196:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '333',
  routine: 'auth_failed'
}
```

I'm not sure where typeorm is getting this `runner` user from. Here is my `ormsettings.js` file:

```js
const databaseURL = (() => {
  switch (process.env.NODE_ENV) {
    case 'production':
      return process.env.DATABASE_URL;
    case 'development':
      return 'postgres://typeorm:password@localhost:5432/todo';
    case 'test':
      return 'postgres://typeorm:password@localhost:5432/todo-test';
  }
})();

module.exports = {
  type: 'postgres',
  url: databaseURL,
  logging: false,
  entities: ['src/entity/*.js'],
  subscribers: ['src/subscriber/*.ts'],
  migrations: ['src/migrations/*.ts'],
  entities: [__dirname + '/src/entity/*.{ts, js}'],
  cli: {
    entitiesDir: './src/entity',
    migrationsDir: './src/migrations',
    subscribersDir: './src/subscriber',
  },
};
```

And here is my workflow file:
```yaml
name: Development(Server)

on: 
  push:
    paths:
      - 'packages/server/**'
      - '.github/workflows/server-development.yml'
    branches-ignore:
      - master
      
jobs:
  development:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: typeorm
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todo-test
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.0.0'
      - run: yarn install
      - run: yarn lint:server
      - run: yarn test:server
```

Can someone shed a light for me? Thanks in advance
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
