### ISSUE TITLE
Create database on postgres sql using docker

### ISSUE THREAD

**Issue by Cristuker** [typeorm/typeorm#6679]
**Issue type:**

[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I need to run a migration to create a database, but after i run i try to connect and i receive the error "this database dont exists".
I am using postgres on docker.

```javascript
import { MigrationInterface, QueryRunner } from 'typeorm';

export default class createDatabase1599495342723 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createDatabase('database_todo', true);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropDatabase('database_todo');
  }
}

```
My ormconfig.json file

```javascript
{
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "postgres",
    "password": "todo123",
    "entities": ["entity/*.js"],
    "synchronize": true,
    "migrationsTableName": "custom_migration_table",
    "migrations": ["./src/database/migrations/*.ts"],
    "cli": {
        "migrationsDir": "./src/database/migrations"
    }
}

```

I also try to run inside a queryRunner.query("CREATE DATABASE IF NOT EXISTS database_todo") and dropDatabase to down, but i have the error "dont can run CREATE DATABASE INSIDE A TRANSACTION"

**Comment by guiaramos** [comment]
This example may help you:
https://github.com/guiaramos/ts-graphql-server

```yaml
# docker-compose.yml
version: '3.8'
services:
  postgres-ts:
    image: postgres:11 # use 11th official postgres version
    ports:
      - 5432:5432
    env_file:
      - .env # configure postgres
    volumes:
      - pg_data:/var/lib/postgres/data # persist data even if container shuts down

volumes:
  pg_data: # named volumes can be managed easier using docker-compose
```
