### ISSUE TITLE
Update docker image that generated by typeorm cli: `npx typeorm --init docker`

### ISSUE THREAD

**Issue by dafujii** [typeorm/typeorm#9326]
### The Problem

Docker image that generated by TypeORM CLI is old.

example:
- `npx typeorm --init docker`
- open docker-compose.yml
```yaml
version: '3'
services:

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
```

I think `image: "postgres:9.6.1"` is old. So I want to update.

### The Solution

Update `getDockerComposeTemplate()` to use `latest`.

https://github.com/typeorm/typeorm/blob/master/src/commands/InitCommand.ts#L521

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.
